[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astronomy-feeds",
]

[tool.uv.sources]
astronomy-feeds = { git = "https://github.com/bluesky-astronomy/astronomy-feeds.git" }
